name: Increment Tag on Push to Main
on:
  push:
    branches:
      - main

jobs:
  increment_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get the latest tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Latest tag is $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Increment the tag
        id: new_tag
        run: |
          old_tag=${{ steps.latest_tag.outputs.latest_tag }}
          IFS='.' read -r -a tag_parts <<< "$old_tag"
          major=${tag_parts[0]:1}
          minor=${tag_parts[1]}
          patch=${tag_parts[2]}
          
          # Increment patch
          # patch=$((patch + 1))
          new_tag="v${major}.${minor}.${patch}"
          echo "New tag is $new_tag"
          echo "::set-output name=new_tag::$new_tag"

      - name: Create and push new tag
        run: |
          new_tag=${{ steps.new_tag.outputs.new_tag }}
          git tag $new_tag
          git push origin $new_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}