name: Increment Tag with RC Suffix
on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  increment_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0-rc")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT  # Use GITHUB_OUTPUT to set output

      - name: Increment the tag
        run: |
          old_tag="${{ steps.latest_tag.outputs.latest_tag }}"
          tag_base=$(echo $old_tag | cut -d'-' -f 1)  # Extract base version
          IFS='.' read -r -a tag_parts <<< "$tag_base"
          major=${tag_parts[0]:1}
          minor=${tag_parts[1]}
          patch=${tag_parts[2]}
          
          # Increment patch
          patch=$((patch + 1))
          new_tag="v${major}.${minor}.${patch}-rc"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT  # Use GITHUB_OUTPUT for new tag

      - name: Create and push new tag
        run: |
          new_tag="${{ steps.increment_tag.outputs.new_tag }}"  # Access via GITHUB_OUTPUT
          git tag $new_tag
          git push origin $new_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
